// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package web

import (
	"github.com/brycedarling/go-practical-microservices/internal/infrastructure/config"
)

// Injectors from inject_web_api.go:

// InitializeAPI ...
func InitializeAPI(conf *config.Config) (API, func(), error) {
	homeHandler := NewHomeHandler(conf)
	viewingHandler := NewViewingHandler(conf)
	registerHandler := NewRegisterHandler(conf)
	authenticationHandler := NewAuthenticationHandler(conf)
	handlers := NewHandlers(homeHandler, viewingHandler, registerHandler, authenticationHandler)
	webAPI, cleanup, err := NewAPI(conf, handlers)
	if err != nil {
		return nil, nil, err
	}
	return webAPI, func() {
		cleanup()
	}, nil
}
