// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: practical.proto

package practicalpb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Viewing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideosWatched int32 `protobuf:"varint,1,opt,name=videos_watched,json=videosWatched,proto3" json:"videos_watched,omitempty"`
}

func (x *Viewing) Reset() {
	*x = Viewing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_practical_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Viewing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Viewing) ProtoMessage() {}

func (x *Viewing) ProtoReflect() protoreflect.Message {
	mi := &file_practical_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Viewing.ProtoReflect.Descriptor instead.
func (*Viewing) Descriptor() ([]byte, []int) {
	return file_practical_proto_rawDescGZIP(), []int{0}
}

func (x *Viewing) GetVideosWatched() int32 {
	if x != nil {
		return x.VideosWatched
	}
	return 0
}

type ViewingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ViewingRequest) Reset() {
	*x = ViewingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_practical_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewingRequest) ProtoMessage() {}

func (x *ViewingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_practical_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewingRequest.ProtoReflect.Descriptor instead.
func (*ViewingRequest) Descriptor() ([]byte, []int) {
	return file_practical_proto_rawDescGZIP(), []int{1}
}

type ViewingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Viewing *Viewing `protobuf:"bytes,1,opt,name=viewing,proto3" json:"viewing,omitempty"`
}

func (x *ViewingResponse) Reset() {
	*x = ViewingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_practical_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewingResponse) ProtoMessage() {}

func (x *ViewingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_practical_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewingResponse.ProtoReflect.Descriptor instead.
func (*ViewingResponse) Descriptor() ([]byte, []int) {
	return file_practical_proto_rawDescGZIP(), []int{2}
}

func (x *ViewingResponse) GetViewing() *Viewing {
	if x != nil {
		return x.Viewing
	}
	return nil
}

type RecordViewingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoId string `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
}

func (x *RecordViewingRequest) Reset() {
	*x = RecordViewingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_practical_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordViewingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordViewingRequest) ProtoMessage() {}

func (x *RecordViewingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_practical_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordViewingRequest.ProtoReflect.Descriptor instead.
func (*RecordViewingRequest) Descriptor() ([]byte, []int) {
	return file_practical_proto_rawDescGZIP(), []int{3}
}

func (x *RecordViewingRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type RecordViewingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RecordViewingResponse) Reset() {
	*x = RecordViewingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_practical_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordViewingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordViewingResponse) ProtoMessage() {}

func (x *RecordViewingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_practical_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordViewingResponse.ProtoReflect.Descriptor instead.
func (*RecordViewingResponse) Descriptor() ([]byte, []int) {
	return file_practical_proto_rawDescGZIP(), []int{4}
}

var File_practical_proto protoreflect.FileDescriptor

var file_practical_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x22, 0x30, 0x0a, 0x07,
	0x56, 0x69, 0x65, 0x77, 0x69, 0x6e, 0x67, 0x12, 0x25, 0x0a, 0x0e, 0x76, 0x69, 0x64, 0x65, 0x6f,
	0x73, 0x5f, 0x77, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0d, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x57, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x22, 0x10,
	0x0a, 0x0e, 0x56, 0x69, 0x65, 0x77, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x3f, 0x0a, 0x0f, 0x56, 0x69, 0x65, 0x77, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x07, 0x76, 0x69, 0x65, 0x77, 0x69, 0x6e, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69, 0x63, 0x61, 0x6c,
	0x2e, 0x56, 0x69, 0x65, 0x77, 0x69, 0x6e, 0x67, 0x52, 0x07, 0x76, 0x69, 0x65, 0x77, 0x69, 0x6e,
	0x67, 0x22, 0x31, 0x0a, 0x14, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x56, 0x69, 0x65, 0x77, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x49, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x56, 0x69,
	0x65, 0x77, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xac, 0x01,
	0x0a, 0x10, 0x50, 0x72, 0x61, 0x63, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x42, 0x0a, 0x07, 0x56, 0x69, 0x65, 0x77, 0x69, 0x6e, 0x67, 0x12, 0x19, 0x2e,
	0x70, 0x72, 0x61, 0x63, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x61, 0x63, 0x74,
	0x69, 0x63, 0x61, 0x6c, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x0d, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x56, 0x69, 0x65, 0x77, 0x69, 0x6e, 0x67, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69,
	0x63, 0x61, 0x6c, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x56, 0x69, 0x65, 0x77, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x61, 0x63, 0x74,
	0x69, 0x63, 0x61, 0x6c, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x56, 0x69, 0x65, 0x77, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x53, 0x5a, 0x51,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x72, 0x79, 0x63, 0x65,
	0x64, 0x61, 0x72, 0x6c, 0x69, 0x6e, 0x67, 0x2f, 0x67, 0x6f, 0x2d, 0x70, 0x72, 0x61, 0x63, 0x74,
	0x69, 0x63, 0x61, 0x6c, 0x2d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69, 0x63,
	0x61, 0x6c, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x72, 0x61, 0x63, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_practical_proto_rawDescOnce sync.Once
	file_practical_proto_rawDescData = file_practical_proto_rawDesc
)

func file_practical_proto_rawDescGZIP() []byte {
	file_practical_proto_rawDescOnce.Do(func() {
		file_practical_proto_rawDescData = protoimpl.X.CompressGZIP(file_practical_proto_rawDescData)
	})
	return file_practical_proto_rawDescData
}

var file_practical_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_practical_proto_goTypes = []interface{}{
	(*Viewing)(nil),               // 0: practical.Viewing
	(*ViewingRequest)(nil),        // 1: practical.ViewingRequest
	(*ViewingResponse)(nil),       // 2: practical.ViewingResponse
	(*RecordViewingRequest)(nil),  // 3: practical.RecordViewingRequest
	(*RecordViewingResponse)(nil), // 4: practical.RecordViewingResponse
}
var file_practical_proto_depIdxs = []int32{
	0, // 0: practical.ViewingResponse.viewing:type_name -> practical.Viewing
	1, // 1: practical.PracticalService.Viewing:input_type -> practical.ViewingRequest
	3, // 2: practical.PracticalService.RecordViewing:input_type -> practical.RecordViewingRequest
	2, // 3: practical.PracticalService.Viewing:output_type -> practical.ViewingResponse
	4, // 4: practical.PracticalService.RecordViewing:output_type -> practical.RecordViewingResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_practical_proto_init() }
func file_practical_proto_init() {
	if File_practical_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_practical_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Viewing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_practical_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_practical_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_practical_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordViewingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_practical_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordViewingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_practical_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_practical_proto_goTypes,
		DependencyIndexes: file_practical_proto_depIdxs,
		MessageInfos:      file_practical_proto_msgTypes,
	}.Build()
	File_practical_proto = out.File
	file_practical_proto_rawDesc = nil
	file_practical_proto_goTypes = nil
	file_practical_proto_depIdxs = nil
}
