// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package viewing

import (
	"github.com/brycedarling/go-practical-microservices/internal/infrastructure/config"
)

// Injectors from inject_viewing_aggregator.go:

// InitializeAggregator ...
func InitializeAggregator(conf *config.Config) *Aggregator {
	aggregator := NewAggregator(conf)
	return aggregator
}
